#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "./fractal.h"
#include "./image.h"


/*
    generate and save the entire fractal
    returns:    0 if successful
                1 otherwise
*/
int generate_fractal(char *file, float width, float height, int workers) {
    /*  TODO: use fork(), mmap(), and munmap() to create a region of shared memory
            to store fractal data, as generated by several child processes  */

	pid_t childpids[workers];

	int stats[workers];

    int row = height/workers;

    color_t *fractal_data = mmap(0, sizeof(color_t)*height*width, PROT_WRITE|PROT_READ, MAP_SHARED|MAP_ANONYMOUS, 33, 0);

   	for(int i = 0; i < workers; i++) {
    	if(!(childpids[i] = fork())) {
    		generate_fractal_region(fractal_data, width, height, row*i, row);
    		munmap(fractal_data, sizeof(color_t)*height*width);
    		return 0;
    	}
    }

    for(int i = 0; i < workers; i++) {
    	waitpid(childpids[i], &stats[i], 0);
    }
    
    if (save_image_data(file, fractal_data, width, height)) {
        		fprintf(stderr, "error saving to image file.\n");
        		munmap(fractal_data, sizeof(color_t)*height*width);
    }	
    
    munmap(fractal_data, sizeof(color_t)*height*width);
    printf("Complete \n");
    return 0;
}
